[profile.default]
src = "contracts"
out = "out"
test = "test"
libs = ["lib"]
script = "scripts"
cache_path = "cache"
gas_reports = ["*"]
via_ir = true
sizes = true
optimizer = true
optimizer_runs = 1000
solc_version = "0.8.23"
ffi = true
fs_permissions = [{ access = "read-write", path = "./scripts/proposals/payload.json"}, { access = "read-write", path = "./scripts/roles.json"}, { access = "read-write", path = "./scripts/proposals/transmuter/selectors.json"}, { access = "read-write", path = "./scripts/proposals/transmuter/selectors_replace.json"}, { access = "read-write", path = "./scripts/proposals/transmuter/selectors_add.json"}]

[fuzz]
runs = 10000

[invariant]
runs = 1000
depth = 30

[rpc_endpoints]
arbitrum = "${ETH_NODE_URI_ARBITRUM}"
gnosis = "https://gnosis.publicnode.com"
mainnet = "${ETH_NODE_URI_MAINNET}"
optimism = "${ETH_NODE_URI_OPTIMISM}"
polygon = "${ETH_NODE_URI_POLYGON}"
fork = "${ETH_NODE_URI_FORK}"
avalanche = "${ETH_NODE_URI_AVALANCHE}"
celo = "${ETH_NODE_URI_CELO}"
polygonzkevm = "${ETH_NODE_URI_POLYGON_ZKEVM}"
bsc = "${ETH_NODE_URI_BSC}"
base = "${ETH_NODE_URI_BASE}"
linea = "${ETH_NODE_URI_LINEA}"
mode = "${ETH_NODE_URI_MODE}"
blast = "${ETH_NODE_URI_BLAST}"

[etherscan]
blast = { key = "${BLAST_ETHERSCAN_API_KEY}", url = "https://api.blastscan.io/api" }


[profile.dev]
optimizer = true
via_ir = false
src = "test"
gas_reports = ["*"]

[profile.dev.fuzz]
runs = 2000

[profile.dev.invariant]
runs = 30
depth = 50
fail_on_revert = false

[profile.ci]
src = "test"
via_ir = false
gas_reports = ["*"]

[profile.ci.fuzz]
runs = 100

[profile.ci.invariant]
runs = 10
depth = 30
fail_on_revert = false
