name: "check-roles"

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  push:

jobs:
  check-roles:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        chain: [1,42161,137,100,43114,8453,56,42220,1101,10,59144]
    steps:
      - uses: actions/checkout@v3

      - name: Run script
        run: yarn check-roles
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          env:
          ETH_NODE_URI_MAINNET: ${{ secrets.ETH_NODE_URI_MAINNET }}
          ETH_NODE_URI_ARBITRUM: ${{ secrets.ETH_NODE_URI_ARBITRUM }}
          ETH_NODE_URI_AVALANCHE: ${{ secrets.ETH_NODE_URI_AVALANCHE }}
          ETH_NODE_URI_OPTIMISM: ${{ secrets.ETH_NODE_URI_OPTIMISM }}
          ETH_NODE_URI_POLYGON: ${{ secrets.ETH_NODE_URI_POLYGON }}
          ETH_NODE_URI_GNOSIS: ${{ secrets.ETH_NODE_URI_GNOSIS }}
          ETH_NODE_URI_BSC: ${{ secrets.ETH_NODE_URI_BSC }}
          ETH_NODE_URI_CELO: ${{ secrets.ETH_NODE_URI_CELO }}
          ETH_NODE_URI_POLYGON_ZKEVM: ${{ secrets.ETH_NODE_URI_POLYGON_ZKEVM }}
          ETH_NODE_URI_BASE: ${{ secrets.ETH_NODE_URI_BASE }}
          ETH_NODE_URI_LINEA: ${{ secrets.ETH_NODE_URI_LINEA }}
          CHAIN_IDS: ${{ matrix.chain }}
